# Site settings
title:          Jamesu.dev
description:    "Blog by James Minsu Jeon"
url:            "https://jamesujeon.github.io"
lang:           "ko_KR"
timezone:       "Asia/Seoul"

# Google Analytics
#google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         jamesujeon
  email:        jamesujeon@gmail.com
  url:          https://jamesujeon.github.io

social:
  name: James Minsu Jeon
  links:
    - https://github.com/jamesujeon

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jemoji

# Permalinks
permalink:      /:year-:month-:day/:title

# Pagination
pagination:
  enabled:      true
  permalink:    /p:num/
  sort_field:   "date"
  sort_reverse: true
  per_page:     5
  trail:
    before:     2
    after:      2

# Excludes
exclude:
  - Gemfile
  - Gemfile.lock
