# Site settings
title:          JAMESU
description:    "Blog by James Minsu Jeon"
url:            "https://jamesujeon.github.io"

# Google Analytics
#google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         jamesujeon
  email:        jamesujeon@gmail.com
  url:          https://jamesujeon.github.io
  github_url:   https://github.com/jamesujeon

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock ]
