# Site settings
title:          Jamesu Devlog
description:    "Dev Blog by James Minsu Jeon"
url:            "https://jamesu.dev"
lang:           "ko_KR"
timezone:       "Asia/Seoul"
home_path:      "/posts"

# Google Analytics
google_analytics: UA-153146788-1

# Author
author:
  name:         jamesujeon
  email:        jamesujeon@gmail.com
  url:          https://jamesu.dev

social:
  name: James Minsu Jeon
  links:
    - https://github.com/jamesujeon
    - https://www.linkedin.com/in/minsu-jeon-532282198
    - https://twitter.com/jamesujeon

# Build settings
markdown:       kramdown
highlighter:    rouge
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-postfiles
  - jekyll-sitemap
  - jemoji

# Permalinks
permalink:      /posts/:year/:month/:day/:title/

# Pagination
pagination:
  enabled:      true
  permalink:    /p:num/
  sort_field:   "date"
  sort_reverse: true
  per_page:     10
  trail:
    before:     2
    after:      2

# Excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
